apiVersion: apps/v1
kind: Deployment
metadata:
  name: productsflaskapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: productsflaskapp
  template:
    metadata:
      labels:
        app: productsflaskapp
    spec:
      containers:
      - name: productsflaskapp
        image: krushikagujarati/productsflaskapp
        ports:
        - containerPort: 5002